version: 2.1
parameters:
  very-secret-key:
    type: string
    default: "<not set>"
  working-directory:
    type: string
    default: "<not set>"

workflows:
  nothing-to-update:
    when:
        or:
          - equal: [ "<not set>", "<< pipeline.parameters.very-secret-key >>" ]
          - equal: [ "<not set>", "<< pipeline.parameters.working-directory >>" ]
    jobs:
      - nothing
  verify-setup:
    when:
      and:
        - not:
            equal: [ "<not set>", "<< pipeline.parameters.very-secret-key >>" ]
        - not:
            equal: [ "<not set>", "<< pipeline.parameters.working-directory >>" ]
    jobs:
      - verify

jobs:
  nothing:
    docker:
        - image: cimg/base:2022.01
    steps:
      - run: echo "No changes in any project detected."
  verify:
    working_directory: "~/<< pipeline.parameters.working-directory >>"
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - run:
          name: Verifying
          command: echo "Soooommmeeeething    << pipeline.parameters.very-secret-key >>"
      - run: pwd
